let books = {
  'GC': {
    chapters: {
      "The Destruction of Jerusalem": "01",
      "Persecution in the First Century": "02",
      "An Era of Spiritual Darkness": "03",
      "The Waldenses": "04",
      "John Wycliffe": "05",
      "Huss and Jerome": "06",
      "Luther's Separation From Rome": "07",
      "Luther Before the Diet": "08",
      "The Swiss Reformer": "09",
      "Progress of Reform in Germany": "10",
      "Protest of the Princes": "11",
      "The French Reformation": "12",
      "The Netherlands and Scandinavia": "13",
      "Later English Reformers": "14",
      "The Bible and the French Revolution": "15",
      "The Pilgrim Fathers": "16",
      "Heralds of the Morning": "17",
      "An American Reformer": "18",
      "Light Through Darkness": "19",
      "A Great Religious Awakening": "20",
      "A Warning Rejected": "21",
      "Prophecies Fulfilled": "22",
      "What is the Sanctuary?": "23",
      "In the Holy of Holies": "24",
      "God's Law Immutable": "25",
      "A Work of Reform": "26",
      "Modern Revivals": "27",
      "Facing Life's Record": "28",
      "The Origin of Evil": "29",
      "Enmity Between Man and Satan": "30",
      "Agency of Evil Spirits": "31",
      "Snares of Satan": "32",
      "The First Great Deception": "33",
      "Can Our Dead Speak to Us?": "34",
      "Liberty of Conscience Threatened": "35",
      "The Impending Conflict": "36",
      "The Scriptures a Safeguard": "37",
      "The Final Warning": "38",
      "The Time of Trouble": "39",
      "God's People Delivered": "40",
      "Desolation of the Earth": "41",
      "The Controversy Ended": "42",
    }
  },
  'AA': {
    chapters: {
      "Chapter 1":""
    }
  }
}
let days = [
{ day: 01, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 02, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 03, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 04, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 05, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 06, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 07, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 08, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 09, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 10, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 11, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 12, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 13, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 14, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 15, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 16, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 17, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 18, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 19, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 20, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 21, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 22, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 23, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 24, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 25, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 26, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 27, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 28, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 29, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 30, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 31, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 32, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 33, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 34, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 35, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 36, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 37, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 38, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 39, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 40, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 41, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 42, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 43, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 44, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 45, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 46, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 47, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 48, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 49, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 50, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 51, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 52, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 53, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 54, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 55, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 56, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 57, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 58, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 59, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 60, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 61, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 62, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 63, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 64, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 65, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 66, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 67, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 68, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 69, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 70, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 71, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 72, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 73, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 74, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 75, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 76, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 77, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 78, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 79, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 80, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 81, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 82, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 83, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 84, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 85, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 86, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 87, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 88, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 89, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 90, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 91, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 92, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 93, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 94, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 95, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 96, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 97, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 98, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 99, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 100, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 101, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 102, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 103, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 104, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 105, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 106, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 107, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 108, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 109, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 110, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 111, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 112, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 113, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 114, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 115, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 116, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 117, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 118, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 119, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 120, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 121, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 122, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 123, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 124, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 125, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 126, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 127, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 128, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 129, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 130, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 131, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 132, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 133, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 134, sopBook: 'AA', sopPages: '145-150b', sopChapter: Object.keys(books['AA'].chapters)[0]},
{ day: 135, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 136, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 137, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 138, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 139, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 140, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 141, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 142, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 143, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 144, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 145, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 146, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 147, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 148, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 149, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 150, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 151, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 152, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 153, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 154, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 155, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 156, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 157, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 158, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 159, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 160, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 161, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 162, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 163, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 164, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 165, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 166, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 167, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 168, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 169, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 170, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 171, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 172, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 173, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 174, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 175, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 176, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 177, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 178, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 179, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 180, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 181, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 182, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 183, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 184, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 185, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 186, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 187, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 188, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 189, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 190, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 191, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 192, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 193, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 194, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 195, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 196, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 197, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 198, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 199, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 200, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 201, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 202, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 203, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 204, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 205, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 206, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 207, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 208, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 209, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 210, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 211, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 212, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 213, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 214, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 215, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 216, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 217, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 218, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 219, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 220, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 221, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 222, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 223, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 224, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 225, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 226, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 227, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 228, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 229, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 230, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 231, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 232, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 233, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 234, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 235, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 236, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 237, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 238, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 239, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 240, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 241, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 242, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 243, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 244, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 245, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 246, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 247, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 248, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 249, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 250, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 251, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 252, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 253, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 254, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 255, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 256, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 257, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 258, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]},
{ day: 259, sopBook: 'GC', sopPages: '145-150b', sopChapter: Object.keys(books['GC'].chapters)[0]}
]


let getDay = function() {
    var now = new Date();
    var start = new Date(now.getFullYear(), 0, 0);
    var diff = now - start;
    var oneDay = 1000 * 60 * 60 * 24;
    var day = Math.floor(diff / oneDay);
    console.log('Day of year: ' + day);
    return day;
}
let today = days.find((day) => day.day === getDay())


console.log(getDay())
let readingsElement = document.body.querySelector('#readings')

let title = document.createElement('a')
title.innerText = '' + today.day + ' ' + today.sopBook + ' ' + today.sopChapter + ' ' + today.sopPages
title.setAttribute('href', `https://www.preparingforeternity.com/${today.sopBook.toLowerCase()}/${today.sopBook.toLowerCase()}${books[today.sopBook].chapters[today.sopChapter]}.htm`)

let iframe = document.createElement('iframe')
iframe.setAttribute('src',`en_${today.sopBook.toLowerCase()}.pdf`)
iframe.setAttribute('title', 'Reading Frame')
iframe.setAttribute('style', 'border:none; width: 100%; height: 40rem')
window.find(today.sopPages)


readingsElement.appendChild(title)
readingsElement.appendChild(iframe)
readingsElement.appendChild()
$("body").on('click', "#getReading", function(){
    console.log('clicked')
    $.get("https://www.preparingforeternity.com/pk/pk08.htm", function(data, status){
      alert("Data: " + data + "\nStatus: " + status);
      console.log(data)
    });
  });
readingsElement.appendChild(title)
